[package]
name = "keybroker-app"
version = "0.1.0"
edition = "2021"
authors = ["Veraison Project Contributors"]
description = "Simple command-line application demonstrating the keybroker."
license = "Apache-2.0"
repository = "https://github.com/veraison/keybroker-demo"
readme = "README.md"
keywords = ["security", "service", "attestation"]
categories = ["cryptography", "hardware-support"]

[dependencies]
keybroker-client = { path = "../keybroker-client" }
keybroker-common = { path = "../keybroker-common" }
reqwest = { version = "0.12.5", features = ["json", "rustls-tls", "blocking"] }
serde = "1.0.204"
rsa = "0.9.6"
sha2 = "0.10.8"
rand = "0.8.5"
base64 = "0.22.1"
mime = "0.3.4"